### ISSUE TITLE
wrong visualization

### ISSUE THREAD

**Issue by ghost** [BlueMetal/iot-edge-dynocard#5]
Hi
I used this tutorial but I don't see the correct visualization I see some thing as below what should I do:

![Capture](https://user-images.githubusercontent.com/49042670/56688328-acfe0680-6695-11e9-9732-a42018c09b5d.PNG)

**Comment by dtjensen** [comment]
The visual might need to be updated. Can you give me the specific steps you performed to get to this point?

**Comment by ghost** [comment]
Thank you for your response. Yes I did as the tutorial and after that I
defined the different fields for that.

**Comment by NathanParsonKoroso** [comment]
Hello @rezamahdiani 
A few questions for you:

- Can you please provide more information as to what you expected vs what you saw?
- What is the data source your are using? 
- Can you replicate the issue using a different data source?
- Can you supply the data to me so I can debug with it?

This information will allow me to diagnose the issue better. Thanks.

**Comment by ghost** [comment]
Hi
Thanks a lot for your reply. my problem solved.

**Comment by NathanParsonKoroso** [comment]
@rezamahdiani Great! Could you please mark this as "closed" so it clears our logs? Thanks for the fast reply also

**Comment by dtjensen** [comment]
@rezamahdiani Could you also post the resolution to issue, just for future reference?

**Comment by dtjensen** [comment]
Closing as this seems to be resolved.
